#!/bin/bash
# sensors-detect-once.sh — run `sensors-detect --auto` exactly once, guarded (Lindos SPEC §11).
#
# Called by lindos-tune's postinst (only outside a chroot) and by
# lindos-sensors-detect.service at first boot.  Never probes inside a chroot/container, never
# runs twice (marker /var/lib/lindos-tune/sensors-detect.done), and does not run when
# lm-sensors was already configured by the user (sensors-detect output present).
# Exit code is always 0 unless --strict is given: sensor detection is best effort.
set -Eeuo pipefail

MARKER="/var/lib/lindos-tune/sensors-detect.done"
STATE_DIR="/var/lib/lindos-tune"
LOG_DIR="/var/log/lindos"
LOG_FILE="${LOG_DIR}/sensors-detect.log"
STRICT=0
FORCE=0

log() {
    printf 'lindos-tune sensors: %s\n' "$*" >&2
    if [ -d "${LOG_DIR}" ]; then
        printf '%s %s\n' "$(date '+%F %T')" "$*" >>"${LOG_FILE}" 2>/dev/null || true
    fi
}

die() {
    log "error: $*"
    if [ "${STRICT}" = 1 ]; then
        exit 1
    fi
    exit 0
}

usage() {
    cat <<'EOF'
usage: sensors-detect-once.sh [--force] [--strict]
  --force   run even if the marker file exists or lm-sensors looks configured
  --strict  exit non-zero on failure (default: always exit 0, best effort)
EOF
}

in_chroot() {
    if command -v systemd-detect-virt >/dev/null 2>&1 && systemd-detect-virt --quiet --chroot; then
        return 0
    fi
    if command -v ischroot >/dev/null 2>&1 && ischroot; then
        return 0
    fi
    if command -v systemd-detect-virt >/dev/null 2>&1 && systemd-detect-virt --quiet --container; then
        return 0
    fi
    [ ! -d /run/systemd/system ]
}

already_configured() {
    # sensors-detect writes "# Generated by sensors-detect" into /etc/modules (Debian/Ubuntu)
    # or /etc/modules-load.d/lm-sensors.conf, and /etc/conf.d/lm_sensors on other distros.
    grep -qs 'Generated by sensors-detect' /etc/modules /etc/modules-load.d/*.conf 2>/dev/null
}

main() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --force) FORCE=1 ;;
            --strict) STRICT=1 ;;
            -h|--help) usage; exit 0 ;;
            *) usage; exit 2 ;;
        esac
        shift
    done
    if [ "$(id -u)" != 0 ]; then
        die "must run as root"
    fi
    if in_chroot; then
        log "inside a chroot/container: not probing hardware (deferred to first boot)"
        exit 0
    fi
    mkdir -p "${STATE_DIR}" "${LOG_DIR}" 2>/dev/null || true
    if [ "${FORCE}" != 1 ] && [ -e "${MARKER}" ]; then
        log "already done (${MARKER}); use --force to re-run"
        exit 0
    fi
    if ! command -v sensors-detect >/dev/null 2>&1; then
        die "sensors-detect not installed (package lm-sensors)"
    fi
    if [ "${FORCE}" != 1 ] && already_configured; then
        log "lm-sensors already configured by sensors-detect; leaving it alone"
        : >"${MARKER}"
        exit 0
    fi
    log "running sensors-detect --auto (non-interactive, safe probes only)"
    local rc=0
    if command -v timeout >/dev/null 2>&1; then
        timeout 180 sensors-detect --auto >>"${LOG_FILE}" 2>&1 || rc=$?
    else
        sensors-detect --auto >>"${LOG_FILE}" 2>&1 || rc=$?
    fi
    : >"${MARKER}"
    if [ "${rc}" != 0 ]; then
        die "sensors-detect exited ${rc} (see ${LOG_FILE})"
    fi
    # load what was detected without a reboot
    if command -v systemctl >/dev/null 2>&1; then
        systemctl restart systemd-modules-load.service >/dev/null 2>&1 || true
        if systemctl cat lm-sensors.service >/dev/null 2>&1; then
            systemctl restart lm-sensors.service >/dev/null 2>&1 || true
        fi
    fi
    log "done — try: sensors  (or: lindos-tune fan list)"
    exit 0
}

main "$@"
