#!/usr/bin/env python3
"""taskbar-fallback.py - a Lindos taskbar that still has a window list without xfce4-docklike-plugin.

Every shipped layout puts Docklike (open windows + pinned apps) in slot plugin-2.  Ubuntu 24.04 "noble" does not
package that plugin (only 25.10+ does), so on a noble-based Lindos the slot stays empty and a fresh session has no
window buttons and no pinned apps.  xfce4-panel's own ``tasklist`` and ``launcher`` plugins are always installed:
this tool rewrites a layout to use them - the task list in the Docklike slot, one launcher per pinned app that is
installed - and drops the expanding separators (the task list expands by itself, so a centred bar is not possible).
When the plugin does get packaged nothing changes: ``status`` says ``docklike`` and the shipped layout is used as is.

Usage
    taskbar-fallback.py status  [--root DIR]
    taskbar-fallback.py convert PANEL_DIR OUT_DIR [--root DIR] [--home DIR] [--all-pins]

``status`` prints ``docklike`` or ``tasklist`` (``LINDOS_TASKBAR`` overrides it).  ``convert`` reads
``PANEL_DIR/xfce4-panel.xml`` (+ the rc files) and writes the same set to OUT_DIR with the task list in place of
Docklike; pins come from ``docklike-<id>.rc`` and are kept only when their .desktop file is installed
(``--all-pins`` keeps every one).  Pure stdlib.  Exit codes: 0 ok, 1 error, 2 usage.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List, Optional, Sequence, Tuple

DOCKLIKE_DESKTOP = "usr/share/xfce4/panel/plugins/docklike.desktop"
APP_DIRS = ("usr/share/applications", "usr/local/share/applications", "var/lib/flatpak/exports/share/applications")
HOME_APP_DIRS = (".local/share/applications", ".local/share/flatpak/exports/share/applications")

#: icon-only, flat buttons (Windows-style); everything else stays at xfce4-panel's defaults
TASKLIST_PROPS: Tuple[Tuple[str, str, str], ...] = (
    ("show-labels", "bool", "false"),
    ("flat-buttons", "bool", "true"),
    ("show-handle", "bool", "false"),
    ("include-all-workspaces", "bool", "false"),
)

NOTE = ("Generated by taskbar-fallback.py: this system has no xfce4-docklike-plugin, so xfce4-panel's own task list "
        "and launchers stand in for it.")


def _root(root: Optional[str]) -> str:
    return root if root is not None else os.environ.get("LINDOS_ROOT") or "/"


def docklike_installed(root: Optional[str] = None) -> bool:
    return os.path.isfile(os.path.join(_root(root), DOCKLIKE_DESKTOP))


def taskbar_kind(root: Optional[str] = None) -> str:
    forced = os.environ.get("LINDOS_TASKBAR", "").strip().lower()
    if forced in ("docklike", "tasklist"):
        return forced
    return "docklike" if docklike_installed(root) else "tasklist"


# --- pins -------------------------------------------------------------------------------------
def parse_pins(rc_text: str) -> List[str]:
    """The ``pinned=a.desktop;b.desktop;`` line of a docklike rc file."""
    m = re.search(r"^pinned=(.*)$", rc_text, flags=re.M)
    return [p.strip() for p in (m.group(1) if m else "").split(";") if p.strip()]


def pin_installed(pin: str, root: Optional[str] = None, home: Optional[str] = None) -> bool:
    base = _root(root)
    home = home if home is not None else (os.environ.get("LINDOS_HOME") or os.path.expanduser("~"))
    dirs = [os.path.join(base, d) for d in APP_DIRS] + [os.path.join(home, d) for d in HOME_APP_DIRS]
    return any(os.path.isfile(os.path.join(d, pin)) for d in dirs)


# --- layout rewrite ---------------------------------------------------------------------------
def _prop(parent: ET.Element, name: str, kind: str, value: Optional[str] = None) -> ET.Element:
    el = ET.SubElement(parent, "property", {"name": name, "type": kind})
    if value is not None:
        el.set("value", value)
    return el


def _plugin_table(plugins: ET.Element) -> Dict[int, ET.Element]:
    table: Dict[int, ET.Element] = {}
    for el in plugins.findall("property"):
        m = re.match(r"^plugin-(\d+)$", el.get("name") or "")
        if m:
            table[int(m.group(1))] = el
    return table


def _ids(ids_prop: ET.Element) -> List[int]:
    return [int(v.get("value") or 0) for v in ids_prop.findall("value")]


def _set_ids(ids_prop: ET.Element, ids: Sequence[int]) -> None:
    for v in list(ids_prop):
        ids_prop.remove(v)
    for pid in ids:
        ET.SubElement(ids_prop, "value", {"type": "int", "value": str(pid)})


def _expands(plugin: ET.Element) -> bool:
    for child in plugin.findall("property"):
        if child.get("name") == "expand":
            return (child.get("value") or "").lower() == "true"
    return False


def convert_root(root: ET.Element, pins: Sequence[str]) -> bool:
    """Rewrite the ``xfce4-panel`` channel *root* in place; False when it has no docklike plugin."""
    plugins = next((p for p in root.findall("property") if p.get("name") == "plugins"), None)
    panels = next((p for p in root.findall("property") if p.get("name") == "panels"), None)
    if plugins is None or panels is None:
        return False
    table = _plugin_table(plugins)
    docks = sorted(pid for pid, el in table.items() if el.get("value") == "docklike")
    if not docks:
        return False
    next_id = max(list(table) + [10]) + 1
    launchers_done = False
    for dock in docks:
        for child in list(table[dock]):
            table[dock].remove(child)
        table[dock].set("value", "tasklist")
        for name, kind, value in TASKLIST_PROPS:
            _prop(table[dock], name, kind, value)
    for panel in panels.findall("property"):
        ids_prop = next((p for p in panel.findall("property") if p.get("name") == "plugin-ids"), None)
        if ids_prop is None:
            continue
        ids = _ids(ids_prop)
        here = [i for i in ids if i in docks]
        if not here:
            continue
        first = ids.index(here[0])
        if not launchers_done:
            new_ids: List[int] = []
            for pin in pins:
                el = _prop(plugins, "plugin-%d" % next_id, "string", "launcher")
                items = _prop(el, "items", "array")
                ET.SubElement(items, "value", {"type": "string", "value": pin})
                new_ids.append(next_id)
                next_id += 1
            ids[first:first] = new_ids
            first += len(new_ids)
            launchers_done = True
        keep: List[int] = []
        for pos, pid in enumerate(ids):
            plugin = table.get(pid)
            if plugin is not None and plugin.get("value") == "separator" and _expands(plugin):
                if pos < first:
                    for child in plugin.findall("property"):
                        if child.get("name") == "expand":
                            child.set("value", "false")
                else:
                    plugins.remove(plugin)     # nothing may share the space the task list takes
                    continue
            keep.append(pid)
        _set_ids(ids_prop, keep)
    return True


def _parse(path: str) -> ET.Element:
    return ET.parse(path).getroot()


def _write(root: ET.Element, path: str) -> None:
    ET.indent(root, space="  ")
    text = '<?xml version="1.0" encoding="UTF-8"?>\n\n<!--\n  %s\n-->\n%s\n' % (NOTE, ET.tostring(root, encoding="unicode"))
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def convert_dir(panel_dir: str, out_dir: str, root: Optional[str] = None, home: Optional[str] = None,
                all_pins: bool = False) -> List[str]:
    """Write the task-list variant of *panel_dir* to *out_dir*; returns the launchers that were added."""
    xml_in = os.path.join(panel_dir, "xfce4-panel.xml")
    tree = _parse(xml_in)
    rc_pins: List[str] = []
    for name in sorted(os.listdir(panel_dir)):
        if re.match(r"^docklike-\d+\.rc$", name) and not rc_pins:
            with open(os.path.join(panel_dir, name), encoding="utf-8") as fh:
                rc_pins = parse_pins(fh.read())
    pins = rc_pins if all_pins else [p for p in rc_pins if pin_installed(p, root, home)]
    os.makedirs(out_dir, exist_ok=True)
    for name in sorted(os.listdir(panel_dir)):
        src = os.path.join(panel_dir, name)
        if name == "xfce4-panel.xml" or re.match(r"^docklike-\d+\.rc$", name):
            continue
        dst = os.path.join(out_dir, name)
        if os.path.isdir(src):
            shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
            shutil.copyfile(src, dst)
    if not convert_root(tree, pins):
        shutil.copyfile(xml_in, os.path.join(out_dir, "xfce4-panel.xml"))     # nothing to replace
        for name in sorted(os.listdir(panel_dir)):
            if re.match(r"^docklike-\d+\.rc$", name):
                shutil.copyfile(os.path.join(panel_dir, name), os.path.join(out_dir, name))
        return []
    _write(tree, os.path.join(out_dir, "xfce4-panel.xml"))
    return pins


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="taskbar-fallback.py", description="Taskbar layout without xfce4-docklike-plugin")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_status = sub.add_parser("status", help="print docklike or tasklist")
    p_status.add_argument("--root")
    p_conv = sub.add_parser("convert", help="write the task-list variant of a panel/ directory")
    p_conv.add_argument("panel_dir")
    p_conv.add_argument("out_dir")
    p_conv.add_argument("--root")
    p_conv.add_argument("--home")
    p_conv.add_argument("--all-pins", action="store_true", help="keep pins whose .desktop file is not installed")
    args = parser.parse_args(argv)
    try:
        if args.cmd == "status":
            print(taskbar_kind(args.root))
            return 0
        pins = convert_dir(args.panel_dir, args.out_dir, args.root, args.home, args.all_pins)
        sys.stderr.write("taskbar-fallback: %s -> %s (%d launcher(s))\n" % (args.panel_dir, args.out_dir, len(pins)))
        return 0
    except (OSError, ET.ParseError, ValueError) as exc:
        sys.stderr.write("taskbar-fallback: ERROR: %s\n" % exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
