"""msix.py: bundles (selection, identity checks, stored-entry rules), flat bundles and upload files.

Fixtures are generated by test_msix_builders.py (never vendored).  Hermetic: tmp dirs only, no Wine.
"""
from __future__ import annotations

import importlib.util
import os
import sys
import zipfile
from pathlib import Path

import pytest

from lindos_compat import msix


def _builders():
    name = "lindos_test_msix_builders"
    if name not in sys.modules:
        spec = importlib.util.spec_from_file_location(name, Path(__file__).with_name("test_msix_builders.py"))
        mod = importlib.util.module_from_spec(spec)
        sys.modules[name] = mod
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return sys.modules[name]


B = _builders()
Inner = B.Inner
PID = msix.publisher_id(B.PUBLISHER)
X64 = B.arch_package("x64")
X86 = B.arch_package("x86")
ARM64 = B.arch_package("arm64")


@pytest.fixture(autouse=True)
def _sandbox(home: Path) -> Path:
    return home


@pytest.fixture()
def prefix(tmp_path: Path) -> Path:
    return tmp_path / "prefixes" / f"{B.NAME}_{PID}"


def _bundle(tmp_path: Path, inners, fname: str = "Contoso.msixbundle", **kw) -> Path:
    return B.write(tmp_path / "dl" / fname, B.make_bundle(inners, **kw))


def _windowsapps(prefix: Path) -> Path:
    return prefix / "drive_c" / "Program Files" / "WindowsApps"


# --------------------------------------------------------------------------- #
# (c) x86 / x64 / arm64 + resource package, stored inner packages
# --------------------------------------------------------------------------- #
def test_bundle_is_classified_by_content(tmp_path: Path) -> None:
    data = B.standard_bundle()
    assert msix.classify(B.write(tmp_path / "a.msixbundle", data)) == "bundle"
    assert msix.classify(B.write(tmp_path / "Rufus-like.appx", data)) == "bundle"  # .appx that is a bundle


def test_bundle_selects_x64(tmp_path: Path) -> None:
    info = msix.inspect(B.write(tmp_path / "Contoso.msixbundle", B.standard_bundle()))
    assert info.kind == "bundle"
    assert info.selected_package == "Contoso_x64.msix"
    assert (info.arch, info.version, info.bundle_version) == ("x64", B.VERSION, B.BUNDLE_VERSION)
    assert info.package_full_name == f"{B.NAME}_{B.VERSION}_x64__{PID}"
    assert info.status == "partial" and info.apps[0].app_class == "win32"
    assert info.signed
    assert any("picked the x64 build" in w and "arm64" in w for w in info.warnings)


def test_bundle_install_uses_the_x64_package(tmp_path: Path, prefix: Path) -> None:
    inst = msix.install(B.write(tmp_path / "Contoso.msixbundle", B.standard_bundle()), prefix)
    [(app, exe, logo)] = inst.apps
    assert exe.read_bytes() == B.exe("x64 editor")
    assert logo is not None and logo.read_bytes() == B.png("x64-44")
    assert inst.install_dir.name == f"{B.NAME}_{B.VERSION}_x64__{PID}"
    assert not [p for p in _windowsapps(prefix).iterdir() if p.name.startswith(".lindos")]


def test_logo_comes_from_the_largest_resource_package(tmp_path: Path, prefix: Path) -> None:
    path = _bundle(tmp_path, [
        Inner("Contoso_x64.msix", B.arch_package("x64", logos=False)),
        Inner("Contoso_scale-100.msix", B.resource_package(100), type=None, arch="neutral",
              resource_id="split.scale-100", family=None),
        Inner("Contoso_scale-400.msix", B.resource_package(400), type="resource", arch="neutral",
              resource_id="split.scale-400", family=None),
    ])
    inst = msix.install(path, prefix)
    [(_, _, logo)] = inst.apps
    expected = _windowsapps(prefix) / f"{B.NAME}_{B.VERSION}_neutral_split.scale-400_{PID}" / "Assets" / \
        "Square44x44Logo.scale-400.png"
    assert logo == expected and logo.read_bytes() == B.png("res-400")
    assert any("resource package" in n for n in inst.notes)


def test_missing_type_means_resource(tmp_path: Path) -> None:
    path = _bundle(tmp_path, [Inner("Contoso_x64.msix", X64, type=None)])
    with pytest.raises(msix.MsixError, match="only resource packages"):
        msix.inspect(path)


def test_stub_packages_are_skipped(tmp_path: Path) -> None:
    path = _bundle(tmp_path, [Inner("Contoso_x64.msix", X64, b5_stub=True), Inner("Contoso_x86.msix", X86, arch="x86",
                                                                                  b5_stub=False)])
    assert msix.inspect(path).selected_package == "Contoso_x86.msix"
    only_stub = _bundle(tmp_path, [Inner("Contoso_x64.msix", X64, b5_stub=True)], fname="stub.msixbundle")
    with pytest.raises(msix.MsixError, match="stub"):
        msix.inspect(only_stub)


def test_arm_only_bundle_is_explained(tmp_path: Path, prefix: Path) -> None:
    path = _bundle(tmp_path, [Inner("Contoso_arm64.msix", ARM64, arch="arm64"),
                              Inner("Contoso_arm.msix", B.arch_package("arm"), arch="arm"),
                              Inner("Contoso_x86a64.msix", B.arch_package("x86a64"), arch="x86a64")])
    info = msix.inspect(path)
    assert info.status == "unsupported" and "ARM" in info.reason
    assert "arm, arm64, x86a64" in info.reason
    assert info.package_full_name == f"{B.NAME}_{B.BUNDLE_VERSION}_neutral_~_{PID}"
    with pytest.raises(msix.MsixError, match="ARM"):
        msix.install(path, prefix)


def test_neutral_beats_x86_and_desktop_family_breaks_ties(tmp_path: Path) -> None:
    neutral_xbox = B.arch_package("neutral", exe_tag="xbox")
    neutral_desktop = B.arch_package("neutral", exe_tag="desktop")
    path = _bundle(tmp_path, [
        Inner("Contoso_x86.msix", X86, arch="x86"),
        Inner("Contoso_xbox.msix", neutral_xbox, arch="neutral", family="Windows.Xbox"),
        Inner("Contoso_desktop.msix", neutral_desktop, arch="neutral", family="Windows.Desktop"),
    ], root_ns=B.NS_B2018)
    assert msix.inspect(path).selected_package == "Contoso_desktop.msix"


def test_highest_version_wins_a_tie(tmp_path: Path) -> None:
    path = _bundle(tmp_path, [
        Inner("Contoso_old.msix", B.arch_package("x64", version="1.0.0.0"), version="1.0.0.0"),
        Inner("Contoso_new.msix", B.arch_package("x64", version="1.10.0.0"), version="1.10.0.0"),
        Inner("Contoso_mid.msix", B.arch_package("x64", version="1.9.0.0"), version="1.9.0.0"),
    ])
    info = msix.inspect(path)
    assert info.selected_package == "Contoso_new.msix" and info.version == "1.10.0.0"


@pytest.mark.parametrize("inner, words", [
    (Inner("Contoso_x64.msix", B.arch_package("x64", version="1.2.3.1")), "version 1.2.3.1"),
    (Inner("Contoso_x64.msix", X86), "built for x86"),
    (Inner("Contoso_x64.msix", B.arch_package("x64", name="Fabrikam.Other")), "different app"),
    (Inner("Contoso_x64.msix", B.arch_package("x64", publisher="CN=Mallory")), "different publisher"),
    (Inner("Contoso_x64.msix", X64, compress=zipfile.ZIP_DEFLATED), "compressed"),
    (Inner("Contoso_x64.msix", X64, offset=12345), "position"),
    (Inner("Contoso_x64.msix", X64, size=99), "size"),
    (Inner("Contoso_x64.msix", X64, embed=False, offset=4096), "isn't"),
    # Offset="0" is a real (falsy-but-present) declared offset, not "no Offset attribute" -- a
    # manifest claiming the package is embedded at byte 0 while it is absent from the bundle's own
    # zip must still be treated as damaged, not silently fall through to flat-sibling lookup
    # (sec-compat:F2).
    (Inner("Contoso_x64.msix", X64, embed=False, offset=0), "isn't"),
    (Inner("Contoso_x64.msix", B.standard_bundle()), "AppxManifest.xml"),   # bundle inside a bundle
])
def test_inner_package_checks(tmp_path: Path, inner, words: str, prefix: Path) -> None:
    path = _bundle(tmp_path, [inner])
    with pytest.raises(msix.MsixError, match=words):
        msix.inspect(path)
    with pytest.raises(msix.MsixError):
        msix.install(path, prefix)
    assert not _windowsapps(prefix).exists() or not any(_windowsapps(prefix).iterdir())


def test_bundle_manifest_errors(tmp_path: Path) -> None:
    dup = _bundle(tmp_path, [Inner("Contoso_x64.msix", X64), Inner("contoso_X64.msix", X64)], fname="dup.msixbundle")
    with pytest.raises(msix.MsixError, match="twice"):
        msix.inspect(dup)
    bad_name = _bundle(tmp_path, [Inner("Contoso_x64.exe", X64)], fname="bad.msixbundle")
    with pytest.raises(msix.MsixError, match="FileName"):
        msix.inspect(bad_name)
    unknown_ns = _bundle(tmp_path, [Inner("Contoso_x64.msix", X64)], fname="ns.msixbundle",
                         root_ns="http://example.invalid/bundle")
    with pytest.raises(msix.MsixError, match="schema"):
        msix.inspect(unknown_ns)


def test_bundle_percent_encoded_inner_names(tmp_path: Path, prefix: Path) -> None:
    fname = "Contoso Photo Editor [x64].msix"
    path = _bundle(tmp_path, [Inner(fname, X64)])
    assert msix.inspect(path).selected_package == fname
    assert msix.install(path, prefix).apps


# --------------------------------------------------------------------------- #
# (d) flat bundles: the package is a sibling file
# --------------------------------------------------------------------------- #
def _flat(tmp_path: Path, file_name: str, *, sibling: str = "Contoso_x64.msix", data: bytes = X64,
          size="auto") -> Path:
    folder = tmp_path / "flat"
    folder.mkdir(parents=True, exist_ok=True)
    if sibling:
        B.write(folder / sibling, data)
    inner = Inner(file_name, X64, embed=False, offset=None, size=size)
    return B.write(folder / "Contoso.appxbundle", B.make_bundle([inner], root_ns=B.NS_B2017, schema="3.0"))


def test_flat_bundle_uses_the_sibling_file(tmp_path: Path, prefix: Path) -> None:
    path = _flat(tmp_path, "Contoso_x64.msix")
    assert msix.classify(path) == "bundle"
    info = msix.inspect(path)
    assert info.selected_package == "Contoso_x64.msix" and info.status == "partial"
    inst = msix.install(path, prefix)
    assert inst.apps[0][1].read_bytes() == B.exe("x64 editor")


def test_flat_bundle_sibling_lookup_is_case_insensitive(tmp_path: Path) -> None:
    path = _flat(tmp_path, "CONTOSO_X64.MSIX")
    assert msix.inspect(path).selected_package == "CONTOSO_X64.MSIX"


@pytest.mark.parametrize("file_name, words", [
    ("../Contoso_x64.msix", "outside its own folder"),
    ("sub/Contoso_x64.msix", "outside its own folder"),
    ("..\\Contoso_x64.msix", "outside its own folder"),
    ("http://example.invalid/Contoso_x64.msix", "network or the web"),
    ("https://example.invalid/Contoso_x64.msix", "network or the web"),
    ("\\\\fileserver\\share\\Contoso_x64.msix", "network or the web"),
    ("file:Contoso_x64.msix", "network or the web"),
])
def test_flat_bundle_never_leaves_its_folder(tmp_path: Path, file_name: str, words: str) -> None:
    B.write(tmp_path / "Contoso_x64.msix", X64)          # a tempting target one level up
    path = _flat(tmp_path, file_name)
    with pytest.raises(msix.MsixError, match=words):
        msix.inspect(path)


def test_flat_bundle_missing_sibling(tmp_path: Path) -> None:
    path = _flat(tmp_path, "Contoso_x64.msix", sibling="")
    with pytest.raises(msix.MsixError, match="were not downloaded"):
        msix.inspect(path)


def test_flat_bundle_size_mismatch(tmp_path: Path) -> None:
    path = _flat(tmp_path, "Contoso_x64.msix", size=len(X64) + 1)
    with pytest.raises(msix.MsixError, match="different size"):
        msix.inspect(path)


def test_flat_bundle_refuses_symlinked_sibling(tmp_path: Path) -> None:
    real = B.write(tmp_path / "elsewhere" / "Contoso_x64.msix", X64)
    path = _flat(tmp_path, "Contoso_x64.msix", sibling="")
    try:
        os.symlink(real, path.parent / "Contoso_x64.msix")
    except (OSError, NotImplementedError):
        pytest.skip("symbolic links are not available here")
    with pytest.raises(msix.MsixError, match="not a regular file"):
        msix.inspect(path)


# --------------------------------------------------------------------------- #
# (l) .msixupload / .appxupload: one level of recursion
# --------------------------------------------------------------------------- #
def test_upload_with_deflated_bundle(tmp_path: Path, prefix: Path, home: Path) -> None:
    upload = B.write(tmp_path / "Contoso_1.2.3.0.msixupload",
                     B.make_upload([("Contoso.msixbundle", B.standard_bundle()),
                                    ("Contoso.appxsym", b"symbols" * 100)]))
    assert msix.classify(upload) == "upload"
    info = msix.inspect(upload)
    assert info.kind == "upload"
    assert info.selected_package == "Contoso.msixbundle/Contoso_x64.msix"
    assert info.arch == "x64" and info.status == "partial"
    cache = home / ".cache" / "lindos" / "msix"
    assert not cache.exists() or not any(cache.iterdir())      # scratch copy cleaned up
    inst = msix.install(upload, prefix)
    assert inst.apps[0][1].read_bytes() == B.exe("x64 editor")
    assert not [p for p in _windowsapps(prefix).iterdir() if p.name.startswith(".lindos")]


def test_upload_with_packages_picks_x64(tmp_path: Path) -> None:
    upload = B.write(tmp_path / "Contoso.appxupload",
                     B.make_upload([("Contoso_x86.appx", X86), ("Contoso_x64.appx", X64), ("Contoso_arm64.appx", ARM64)],
                                   compress=zipfile.ZIP_STORED))
    info = msix.inspect(upload)
    assert info.selected_package == "Contoso_x64.appx" and info.arch == "x64"


def test_upload_with_only_arm_packages(tmp_path: Path) -> None:
    upload = B.write(tmp_path / "Contoso.msixupload", B.make_upload([("Contoso_arm64.msix", ARM64)]))
    info = msix.inspect(upload)
    assert info.status == "unsupported" and "ARM" in info.reason


def test_upload_recurses_only_once(tmp_path: Path) -> None:
    inner_upload = B.make_upload([("Contoso.msixbundle", B.standard_bundle())])
    upload = B.write(tmp_path / "nested.msixupload", B.make_upload([("Inner.msixupload", inner_upload),
                                                                     ("Trick.msix", inner_upload)]))
    assert msix.classify(upload) == "upload"
    with pytest.raises(msix.MsixError, match="no usable app package"):
        msix.inspect(upload)


def test_flat_bundle_inside_upload_is_refused(tmp_path: Path) -> None:
    flat = B.make_bundle([Inner("Contoso_x64.msix", X64, embed=False, offset=None)])
    upload = B.write(tmp_path / "flat.msixupload", B.make_upload([("Contoso.msixbundle", flat),
                                                                   ("Contoso_x64.msix", X64)]))
    with pytest.raises(msix.MsixError, match="flat bundle"):
        msix.inspect(upload)


def test_upload_respects_max_bytes(tmp_path: Path, prefix: Path) -> None:
    upload = B.write(tmp_path / "Contoso.msixupload", B.make_upload([("Contoso.msixbundle", B.standard_bundle())]))
    with pytest.raises(msix.MsixError, match="limit|no usable"):
        msix.install(upload, prefix, max_bytes=1000)
