"""msix.py: single packages -- classify/inspect/install, app classes, trust, logos, PSF, registry, VFS.

Fixtures are generated by test_msix_builders.py (never vendored).  Hermetic: tmp dirs only, no Wine.
"""
from __future__ import annotations

import importlib.util
import json
import os
import sys
import types
from pathlib import Path
from typing import Dict, List

import pytest

from lindos_compat import msix


def _builders():
    name = "lindos_test_msix_builders"
    if name not in sys.modules:
        spec = importlib.util.spec_from_file_location(name, Path(__file__).with_name("test_msix_builders.py"))
        mod = importlib.util.module_from_spec(spec)
        sys.modules[name] = mod
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return sys.modules[name]


B = _builders()
PID = msix.publisher_id(B.PUBLISHER)
FULL = f"{B.NAME}_{B.VERSION}_x64__{PID}"


@pytest.fixture(autouse=True)
def _sandbox(home: Path) -> Path:
    return home


@pytest.fixture()
def pkg(tmp_path: Path) -> Path:
    return B.write(tmp_path / "in" / "Contoso Photo Editor.msix", B.make_package())


@pytest.fixture()
def prefix(tmp_path: Path) -> Path:
    return tmp_path / "prefixes" / f"{B.NAME}_{PID}"


def _pkg(tmp_path: Path, fname: str = "app.msix", **kw) -> Path:
    return B.write(tmp_path / "in" / fname, B.make_package(**kw))


def _windowsapps(prefix: Path) -> Path:
    return prefix / "drive_c" / "Program Files" / "WindowsApps"


# --------------------------------------------------------------------------- #
# (a) packagedClassicApp: spaces, '[', VFS, logo variants
# --------------------------------------------------------------------------- #
def test_classify_package_by_content_not_extension(pkg: Path, tmp_path: Path) -> None:
    assert msix.classify(pkg) == "package"
    assert msix.classify(B.write(tmp_path / "renamed.zip", pkg.read_bytes())) == "package"
    assert msix.classify(B.write(tmp_path / "fake.msix", b"just text")) == "unknown"


def test_inspect_packaged_classic_app(pkg: Path) -> None:
    info = msix.inspect(pkg)
    assert info.kind == "package"
    assert (info.name, info.publisher, info.version, info.arch, info.resource_id) == (
        B.NAME, B.PUBLISHER, B.VERSION, "x64", "")
    assert info.publisher_id == PID
    assert info.package_full_name == FULL
    assert info.package_family_name == f"{B.NAME}_{PID}"
    assert info.display_name == "Contoso Photo Editor"
    assert info.publisher_display == "Contoso Ltd"
    assert info.status == "partial" and "usually works" in info.reason
    assert info.signed and not info.unsigned_marker and info.store_signals == []
    assert not info.framework and not info.resource_package and info.selected_package is None
    [app] = info.apps
    assert app.app_class == "win32"
    assert app.executable == B.EXE_REL
    assert app.list_entry and not app.console
    assert app.logo == "Assets/Square44x44Logo.targetsize-256_altform-unplated.png"
    json.dumps(info.as_dict())  # JSON-serialisable
    assert msix.trust_label(info) == "Signed (not verified)"
    assert msix.can_try_anyway(info)
    assert msix.prefix_slug(info) == info.package_family_name
    assert msix.aumid(info, app) == f"{B.NAME}_{PID}!App"


def test_install_packaged_classic_app(pkg: Path, prefix: Path) -> None:
    progress: List[tuple] = []
    inst = msix.install(pkg, prefix, on_progress=lambda done, total, name: progress.append((done, total, name)))
    install_dir = _windowsapps(prefix) / FULL
    assert inst.install_dir == install_dir
    # percent-decoded names
    exe_in_pkg = install_dir / "VFS" / "ProgramFilesX64" / "Contoso App" / "Contoso [Beta].exe"
    assert exe_in_pkg.read_bytes() == B.exe("x64 editor")
    assert (install_dir / "VFS" / "ProgramFilesX64" / "Contoso App" / "100% done & ready.txt").is_file()
    # footprint: manifest kept, the rest skipped
    assert (install_dir / "AppxManifest.xml").is_file()
    for name in ("AppxBlockMap.xml", "AppxSignature.p7x", "[Content_Types].xml", "AppxMetadata"):
        assert not (install_dir / name).exists(), name
    # VFS materialised at the Windows locations of this app's own C:\ drive
    drive_c = prefix / "drive_c"
    mapped = drive_c / "Program Files" / "Contoso App" / "Contoso [Beta].exe"
    assert mapped.read_bytes() == B.exe("x64 editor")
    assert (drive_c / "windows" / "syswow64" / "contoso32.dll").read_bytes() == B.exe("sys32")
    assert (drive_c / "windows" / "System32" / "contoso64.dll").is_file()
    assert not (drive_c / "users").exists()  # AppData is never a VFS target
    assert any("AppData" in n for n in inst.notes)
    [(app, exe_path, logo)] = inst.apps
    assert app.id == "App" and exe_path == mapped
    assert logo == install_dir / "Assets" / "Square44x44Logo.targetsize-256_altform-unplated.png"
    assert logo.read_bytes() == B.png("44-256-unplated")
    # progress reached the total; no staging leftovers
    assert progress and progress[-1][0] == progress[-1][1] == sum(len(v) for v in B.desktop_files().values()) + len(
        B.manifest())
    assert not [p for p in _windowsapps(prefix).iterdir() if p.name.startswith(".lindos")]
    json.dumps(inst.as_dict())


def test_install_is_case_insensitive_about_existing_folders(pkg: Path, prefix: Path) -> None:
    drive_c = prefix / "drive_c"
    (drive_c / "windows" / "system32").mkdir(parents=True)
    (drive_c / "program files").mkdir(parents=True)
    inst = msix.install(pkg, prefix)
    assert sorted(n.casefold() for n in os.listdir(drive_c / "windows")).count("system32") == 1
    assert (drive_c / "windows" / "system32" / "contoso64.dll").is_file()
    assert sorted(n.casefold() for n in os.listdir(drive_c)).count("program files") == 1
    assert inst.install_dir.is_dir()


def test_install_replaces_existing_files_and_reinstalls_cleanly(pkg: Path, prefix: Path) -> None:
    old = prefix / "drive_c" / "windows" / "syswow64" / "contoso32.dll"
    old.parent.mkdir(parents=True)
    old.write_bytes(b"old copy")
    first = msix.install(pkg, prefix)
    assert old.read_bytes() == B.exe("sys32")
    assert any("replaced" in n for n in first.notes)
    stale = first.install_dir / "stale.txt"
    stale.write_text("from an earlier install", encoding="utf-8")
    second = msix.install(pkg, prefix)
    assert second.install_dir == first.install_dir and not stale.exists()
    assert not [p for p in _windowsapps(prefix).iterdir() if p.name.startswith(".lindos")]


def test_install_into_32bit_prefix_maps_x86_folders(pkg: Path, prefix: Path) -> None:
    prefix.mkdir(parents=True)
    (prefix / "system.reg").write_text("WINE REGISTRY Version 2\n#arch=win32\n", encoding="utf-8")
    inst = msix.install(pkg, prefix)
    drive_c = prefix / "drive_c"
    assert (drive_c / "windows" / "system32" / "contoso32.dll").read_bytes() == B.exe("sys32")
    assert not (drive_c / "Program Files" / "Contoso App").exists()  # 64-bit folder: stays in the package
    [(_, exe_path, _)] = inst.apps
    assert exe_path == inst.install_dir / "VFS" / "ProgramFilesX64" / "Contoso App" / "Contoso [Beta].exe"
    assert any("ProgramFilesX64" in n for n in inst.notes)


def test_install_refuses_the_shared_prefix(pkg: Path, tmp_path: Path) -> None:
    with pytest.raises(msix.MsixError, match="own C:"):
        msix.install(pkg, tmp_path / "prefixes" / "default")


def test_progress_callback_can_cancel_without_leftovers(pkg: Path, prefix: Path) -> None:
    def cancel(done: int, total: int, name: str) -> None:
        raise KeyboardInterrupt

    with pytest.raises(KeyboardInterrupt):
        msix.install(pkg, prefix, on_progress=cancel)
    assert list(_windowsapps(prefix).iterdir()) == []


def test_install_checks_free_space_first(pkg: Path, prefix: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(msix, "_free_bytes", lambda path: 1024)
    with pytest.raises(msix.MsixError, match="Not enough free disk space"):
        msix.install(pkg, prefix)
    assert not (_windowsapps(prefix) / FULL).exists()


def test_install_refuses_symlink_in_the_c_drive(pkg: Path, prefix: Path, tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    (prefix / "drive_c" / "Program Files").mkdir(parents=True)
    try:
        os.symlink(outside, prefix / "drive_c" / "Program Files" / "Contoso App", target_is_directory=True)
    except (OSError, NotImplementedError):
        pytest.skip("symbolic links are not available here")
    with pytest.raises(msix.MsixError, match="symbolic link"):
        msix.install(pkg, prefix)
    assert list(outside.iterdir()) == []
    assert not (_windowsapps(prefix) / FULL).exists()


def test_launch_info_expands_macros_and_splits_arguments(tmp_path: Path, prefix: Path) -> None:
    attrs = (B.CLASSIC + ' uap11:Parameters="--root &quot;$(package.effectivePath)&quot; $(env:ProgramData) '
             '$(env:USERNAME) $$5" uap11:CurrentDirectoryPath="$(package.installedPath)\\Assets" '
             'desktop4:Subsystem="console"')
    path = _pkg(tmp_path, man=B.manifest(apps=[B.app_xml(attrs=attrs)]))
    inst = msix.install(path, prefix)
    info = msix.launch_info(inst, 0)
    root = msix.package_root_windows(inst.info)
    assert root == "C:\\Program Files\\WindowsApps\\" + FULL
    assert info["args"] == ["--root", root, "C:\\ProgramData", "%USERNAME%", "$5"]
    assert Path(str(info["cwd"])) == inst.install_dir / "Assets"
    assert info["console"] is True and info["list_entry"] is True
    assert info["aumid"] == f"{B.NAME}_{PID}!App" and info["pfn"] == f"{B.NAME}_{PID}"
    assert info["source"] == "msix"
    assert info["exe"] == str(prefix / "drive_c" / "Program Files" / "Contoso App" / "Contoso [Beta].exe")


def test_launch_info_defaults_to_exe_folder(pkg: Path, prefix: Path) -> None:
    inst = msix.install(pkg, prefix)
    info = msix.launch_info(inst)
    assert info["args"] == [] and Path(str(info["cwd"])) == Path(str(info["exe"])).parent


# --------------------------------------------------------------------------- #
# (b) UWP, (h) hosted, (i) Windows 8, partial packages
# --------------------------------------------------------------------------- #
VCLIBS_UWP = ('<PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.30035.0" '
              'Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>')


def test_uwp_app_is_unsupported_and_not_installed(tmp_path: Path, prefix: Path) -> None:
    man = B.manifest(apps=[B.app_xml(exe_rel="Xodo.exe", attrs='EntryPoint="App.App"')],
                     families=("Windows.Universal",), deps=VCLIBS_UWP, caps="")
    path = _pkg(tmp_path, files={"Xodo.exe": B.exe()}, man=man)
    info = msix.inspect(path)
    assert info.apps[0].app_class == "uwp"
    assert info.status == "unsupported"
    assert "Wine has no UWP app model" in info.reason and "lindos-vm" in info.reason
    assert any("expected to fail under Wine" in w for w in info.warnings)
    assert not msix.can_try_anyway(info)
    with pytest.raises(msix.MsixError, match="UWP"):
        msix.install(path, prefix)
    assert not (_windowsapps(prefix) / FULL).exists()


def test_hosted_app_needs_host(tmp_path: Path, prefix: Path) -> None:
    app = ('<Application Id="App" uap10:HostId="PythonHost" uap10:Parameters="app.py">'
           '<uap:VisualElements DisplayName="Hosted" Description="d" BackgroundColor="transparent" '
           'Square150x150Logo="a.png" Square44x44Logo="b.png"/></Application>')
    path = _pkg(tmp_path, files={"app.py": b"print(1)"}, man=B.manifest(apps=[app]))
    info = msix.inspect(path)
    assert info.apps[0].app_class == "needs-host"
    assert info.apps[0].parameters == "app.py"
    assert info.status == "unsupported" and "host runtime" in info.reason
    with pytest.raises(msix.MsixError, match="host runtime"):
        msix.install(path, prefix)


@pytest.mark.parametrize("app_attrs", ['Executable="App.exe" EntryPoint="App.App"',
                                       'Executable="App.exe" EntryPoint="Windows.FullTrustApplication"'])
def test_windows8_manifest_is_always_uwp(tmp_path: Path, app_attrs: str) -> None:
    files = {"App.exe": B.exe(), "Assets/SmallLogo.scale-100.png": B.png("small"), "Assets/Logo.png": B.png("l")}
    path = _pkg(tmp_path, files=files, man=B.win8_manifest(app_attrs))
    info = msix.inspect(path)
    assert info.apps[0].app_class == "uwp"
    assert info.status == "unsupported"
    assert info.arch == "x86" and info.display_name == "Old App"
    assert info.apps[0].logo == "Assets/SmallLogo.scale-100.png"


def test_partial_package_installs_only_desktop_apps(tmp_path: Path, prefix: Path) -> None:
    apps = [B.app_xml("Editor"), B.app_xml("Viewer", exe_rel="Viewer.exe", attrs='EntryPoint="Viewer.App"',
                                           display="Contoso Viewer")]
    files = dict(B.desktop_files(), **{"Viewer.exe": B.exe("uwp")})
    path = _pkg(tmp_path, files=files, man=B.manifest(apps=apps))
    info = msix.inspect(path)
    assert [a.app_class for a in info.apps] == ["win32", "uwp"]
    assert info.status == "partial" and "1 of 2 apps" in info.reason
    assert any("Contoso Viewer" in w for w in info.warnings)
    inst = msix.install(path, prefix)
    assert [a.id for a, _, _ in inst.apps] == ["Editor"]
    assert any("Contoso Viewer" in n and "not installed" in n for n in inst.notes)


# --------------------------------------------------------------------------- #
# app-class rule matrix
# --------------------------------------------------------------------------- #
RFT = '<rescap:Capability Name="runFullTrust"/>'


@pytest.mark.parametrize("attrs, exe_rel, caps, expected", [
    (B.FULLTRUST_EP, "a.exe", RFT, "win32"),
    ('EntryPoint="windows.fullTrustApplication"', "a.exe", RFT, "win32"),       # case-insensitive
    ('EntryPoint="Windows.PartialTrustApplication"', "a.exe", "", "win32"),     # desktop app in a sandbox
    ('uap10:RuntimeBehavior="win32App" uap10:TrustLevel="mediumIL"', "a.exe", RFT, "win32"),
    ('uap10:RuntimeBehavior="packagedClassicApp" uap10:TrustLevel="mediumIL"', "a.exe", RFT, "win32"),
    ('uap10:RuntimeBehavior="packagedClassicApp"', "a.exe", "", "win32"),        # appContainer default
    ('uap10:RuntimeBehavior="windowsApp" EntryPoint="App.App"', "a.exe", "", "uwp"),
    ('uap10:RuntimeBehavior="windowsApp" uap10:TrustLevel="mediumIL" EntryPoint="App.App"', "a.exe", "", "uwp"),
    ('EntryPoint="App.App"', "a.exe", RFT, "uwp"),                                # Executable != win32
    ('StartPage="index.html"', None, "", "uwp"),
    ('previewsecurity2:RuntimeBehavior="appSilo"', "a.exe", RFT, "unknown"),
    ('EntryPoint="Windows.FullTrustApplication" previewsecurity:TrustLevel="appSilo"', "a.exe", RFT, "unknown"),
    ('uap10:RuntimeBehavior="windowsApp" EntryPoint="Windows.FullTrustApplication"', "a.exe", RFT, "unknown"),
    ('uap10:RuntimeBehavior="packagedClassicApp" EntryPoint="App.App"', "a.exe", RFT, "unknown"),
    ('EntryPoint="Windows.FullTrustApplication" uap10:TrustLevel="appContainer"', "a.exe", RFT, "unknown"),
    ('uap10:RuntimeBehavior="someFutureApp"', "a.exe", RFT, "unknown"),
    ('uap10:RuntimeBehavior="packagedClassicApp" uap10:TrustLevel="superIL"', "a.exe", RFT, "unknown"),
    ('', "a.exe", RFT, "win32"),
    ('', "a.exe", "", "unknown"),
    ('uap10:RuntimeBehavior="packagedClassicApp" uap10:TrustLevel="mediumIL"', None, RFT, "unknown"),
    ('uap10:HostId="PwaHost" EntryPoint="Windows.FullTrustApplication"', "a.exe", RFT, "needs-host"),
])
def test_app_class_rule(tmp_path: Path, attrs: str, exe_rel, caps: str, expected: str) -> None:
    path = _pkg(tmp_path, files={"a.exe": B.exe()}, man=B.manifest(apps=[B.app_xml(exe_rel=exe_rel, attrs=attrs)],
                                                                   caps=caps))
    info = msix.inspect(path)
    assert info.apps[0].app_class == expected
    assert info.apps[0].app_class in msix.APP_CLASSES
    assert info.status == ("partial" if expected == "win32" else "unsupported")


def test_sandboxed_and_inconsistent_desktop_apps_are_flagged(tmp_path: Path) -> None:
    sandboxed = _pkg(tmp_path, "s.msix", files={"a.exe": B.exe()},
                     man=B.manifest(apps=[B.app_xml(exe_rel="a.exe", attrs='uap10:RuntimeBehavior="packagedClassicApp"')],
                                    caps=""))
    assert any("sandbox" in w for w in msix.inspect(sandboxed).warnings)
    no_rft = _pkg(tmp_path, "n.msix", files={"a.exe": B.exe()},
                  man=B.manifest(apps=[B.app_xml(exe_rel="a.exe", attrs=B.FULLTRUST_EP)], caps=""))
    assert any("runFullTrust" in w for w in msix.inspect(no_rft).warnings)


# --------------------------------------------------------------------------- #
# (j) BOM, UTF-16, reordered children; components; names; dependencies
# --------------------------------------------------------------------------- #
def test_bom_and_reordered_children(tmp_path: Path) -> None:
    order = ("Applications", "Capabilities", "Dependencies", "Resources", "Properties", "Identity")
    path = _pkg(tmp_path, man=B.manifest(bom=True, order=order))
    info = msix.inspect(path)
    assert info.name == B.NAME and info.apps[0].app_class == "win32" and info.status == "partial"


def test_utf16_manifest(tmp_path: Path) -> None:
    text = B.manifest(prolog='<?xml version="1.0" encoding="utf-16"?>').decode("utf-8")
    path = _pkg(tmp_path, man=text.encode("utf-16"))
    assert msix.inspect(path).name == B.NAME


def test_unknown_manifest_schema_is_refused(tmp_path: Path) -> None:
    man = B.manifest().replace(B.NS_F.encode(), b"http://example.invalid/not-appx")
    with pytest.raises(msix.MsixError, match="schema"):
        msix.inspect(_pkg(tmp_path, man=man))


@pytest.mark.parametrize("props, words", [("<Framework>true</Framework>", "framework"),
                                          ("<ResourcePackage>true</ResourcePackage>", "resource package")])
def test_components_are_not_apps(tmp_path: Path, props: str, words: str, prefix: Path) -> None:
    path = _pkg(tmp_path, man=B.manifest(props_extra=props, apps=[]))
    info = msix.inspect(path)
    assert info.status == "unsupported" and "a component, not an app" in info.reason and words in info.reason
    with pytest.raises(msix.MsixError, match="component"):
        msix.install(path, prefix)


def test_arm_only_package(tmp_path: Path) -> None:
    info = msix.inspect(_pkg(tmp_path, man=B.manifest(arch="arm64")))
    assert info.status == "unsupported" and "ARM" in info.reason and "arm64" in info.reason


def test_ms_resource_names_fall_back(tmp_path: Path) -> None:
    man = B.manifest(display="ms-resource:AppName", pub_display="ms-resource:Publisher",
                     apps=[B.app_xml(display="ms-resource:AppName")])
    info = msix.inspect(_pkg(tmp_path, man=man))
    assert info.display_name == "Photo Editor"
    assert info.apps[0].display_name == "Photo Editor"
    assert info.publisher_display == "Contoso Software"


def test_invalid_identity_is_refused(tmp_path: Path) -> None:
    for bad in ("../../evil", "a", "CON.app", "name."):
        with pytest.raises(msix.MsixError, match="invalid name"):
            msix.inspect(_pkg(tmp_path, man=B.manifest(name=bad)))
    with pytest.raises(msix.MsixError, match="version"):
        msix.inspect(_pkg(tmp_path, man=B.manifest(version="1.2.3.99999")))
    with pytest.raises(msix.MsixError, match="architecture"):
        msix.inspect(_pkg(tmp_path, man=B.manifest(arch="x6_4/..")))


def test_dependency_warnings_and_vcrun_note(tmp_path: Path, prefix: Path) -> None:
    ms = "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
    deps = "".join(f'<PackageDependency Name="{n}" MinVersion="1.0.0.0" Publisher="{ms}"/>' for n in (
        "Microsoft.VCLibs.140.00.UWPDesktop", "Microsoft.UI.Xaml.2.8", "Microsoft.WindowsAppRuntime.1.5",
        "Microsoft.NET.Native.Framework.2.2", "Microsoft.VCLibs.140.00", "Fabrikam.Helper"))
    path = _pkg(tmp_path, man=B.manifest(deps=deps))
    info = msix.inspect(path)
    assert [d["name"] for d in info.dependencies][:2] == ["Microsoft.VCLibs.140.00.UWPDesktop", "Microsoft.UI.Xaml.2.8"]
    assert info.dependencies[0] == {"name": "Microsoft.VCLibs.140.00.UWPDesktop", "publisher": ms,
                                    "min_version": "1.0.0.0"}
    text = "\n".join(info.warnings)
    assert "winetricks vcrun2022" in text
    for name in ("Microsoft.UI.Xaml.2.8", "Microsoft.WindowsAppRuntime.1.5", "Microsoft.NET.Native.Framework.2.2"):
        assert f"Depends on {name}, a Windows app runtime that Wine doesn't provide" in text
    assert text.count("expected to fail under Wine") == 4
    assert "Fabrikam.Helper" in text
    inst = msix.install(path, prefix)
    assert any("winetricks vcrun2022" in n for n in inst.notes)


# --------------------------------------------------------------------------- #
# trust and Store signals
# --------------------------------------------------------------------------- #
def test_unsigned_marker(tmp_path: Path) -> None:
    info = msix.inspect(_pkg(tmp_path, signed=False, man=B.manifest(publisher=f"CN=Contoso, {B.UNSIGNED}")))
    assert not info.signed and info.unsigned_marker
    assert msix.trust_label(info) == f"Unsigned (publisher marked unsigned: {B.UNSIGNED})"
    assert not any("no signature" in w for w in info.warnings)


def test_unsigned_without_marker_is_flagged(tmp_path: Path) -> None:
    info = msix.inspect(_pkg(tmp_path, signed=False))
    assert not info.signed and not info.unsigned_marker
    assert msix.trust_label(info) == "Unsigned (no signature)"
    assert any("no signature" in w for w in info.warnings)


def test_damaged_signature_is_not_counted(tmp_path: Path) -> None:
    info = msix.inspect(_pkg(tmp_path, signed=False, raw_entries=[("AppxSignature.p7x", b"garbage")]))
    assert not info.signed and any("signature file" in w and "damaged" in w for w in info.warnings)


def test_store_signals_are_reported_honestly(tmp_path: Path) -> None:
    man = B.manifest(publisher="CN=728D3E49-73AE-4BBD-BC7C-5885A138F109")
    info = msix.inspect(_pkg(tmp_path, man=man, store_signer=True, code_integrity=True))
    assert info.store_signals == ["store-signer", "code-integrity-catalog", "partner-center-publisher"]
    assert info.publisher_id == "3v3sf0k6w2rec"
    assert any("Microsoft Store" in w and "licence" in w for w in info.warnings)
    assert info.status == "partial" and msix.can_try_anyway(info)  # non-encrypted desktop app: "Try anyway"


def test_gdk_game_signal(tmp_path: Path) -> None:
    files = dict(B.desktop_files(), **{"MicrosoftGame.config": b"<Game/>"})
    info = msix.inspect(_pkg(tmp_path, files=files))
    assert "xbox-gdk-game" in info.store_signals
    assert any("Xbox" in w for w in info.warnings)


# --------------------------------------------------------------------------- #
# logos
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("ref, names, expected", [
    ("Assets\\Logo.png", ["Assets/Logo.scale-100.png", "Assets/scale-200/Logo.png"], "Assets/scale-200/Logo.png"),
    ("assets/logo.png", ["Assets/Logo.targetsize-256_altform-unplated.png", "Assets/Logo.scale-400.png"],
     "Assets/Logo.targetsize-256_altform-unplated.png"),
    ("Images\\Logo.png", ["Images/Logo.contrast-high_scale-400.png", "Images/Logo.scale-200.png"],
     "Images/Logo.scale-200.png"),
    ("A\\L.png", ["A/L.png", "A/L.targetsize-48.png"], "A/L.png"),
    ("A\\L.png", ["A/L.targetsize-48.png", "A/L.targetsize-24_altform-unplated.png"],
     "A/L.targetsize-24_altform-unplated.png"),                     # unplated first (menu icons)
    ("A\\L.png", ["A/L.targetsize-32_altform-unplated.png", "A/L.targetsize-96_altform-unplated.png",
                  "A/L.targetsize-48.png"], "A/L.targetsize-96_altform-unplated.png"),
    ("Assets\\Logo.png", ["Assets/en-us/Logo.scale-200.png"], "Assets/en-us/Logo.scale-200.png"),
    ("Assets\\Logo.png", ["Other/Logo.png", "Assets/Logo.backup.png", "Assets/Logo.png.bak"], ""),
    ("Assets\\Logo.png", ["Assets/Logo.theme-light_scale-400.png", "Assets/Logo.scale-200.png"],
     "Assets/Logo.scale-200.png"),
    ("..\\Logo.png", ["Logo.png"], ""),
    ("", ["Logo.png"], ""),
])
def test_logo_resolution(ref: str, names: List[str], expected: str) -> None:
    assert msix._resolve_logo(ref, names) == expected


def test_store_logo_is_the_last_fallback(tmp_path: Path) -> None:
    files = {"a.exe": B.exe(), "Assets/StoreLogo.scale-100.png": B.png("store")}
    info = msix.inspect(_pkg(tmp_path, files=files, man=B.manifest(apps=[B.app_xml(exe_rel="a.exe")])))
    assert info.apps[0].logo == "Assets/StoreLogo.scale-100.png"


# --------------------------------------------------------------------------- #
# Package Support Framework
# --------------------------------------------------------------------------- #
def _psf_package(tmp_path: Path, config: object) -> Path:
    files = dict(B.desktop_files(), **{"PsfLauncher64.exe": B.exe("psf"), "PsfRuntime64.dll": B.exe("rt")})
    if config is not None:
        files["config.json"] = json.dumps(config).encode("utf-8")
    man = B.manifest(apps=[B.app_xml(exe_rel="PsfLauncher64.exe")])
    return _pkg(tmp_path, files=files, man=man)


def test_psf_launcher_is_resolved_to_the_real_program(tmp_path: Path, prefix: Path) -> None:
    config = {"applications": [{"id": "app", "executable": "%MsixPackageRoot%\\VFS/ProgramFilesX64/Contoso App/"
                                                           "Contoso [Beta].exe",
                                "arguments": '--from-psf "a b"', "workingDirectory": "",
                                "startScript": {"scriptPath": "setup.ps1", "runInVirtualEnvironment": True}}],
              "processes": [{"executable": ".*", "fixups": [{"dll": "FileRedirectionFixup64.dll"}]}]}
    inst = msix.install(_psf_package(tmp_path, config), prefix)
    [(app, exe_path, _)] = inst.apps
    assert exe_path == prefix / "drive_c" / "Program Files" / "Contoso App" / "Contoso [Beta].exe"
    assert app.executable == "VFS\\ProgramFilesX64\\Contoso App\\Contoso [Beta].exe"
    assert app.parameters == '--from-psf "a b"'
    assert msix.launch_info(inst)["args"] == ["--from-psf", "a b"]
    assert any("PowerShell" in n and "skipped" in n for n in inst.notes)


@pytest.mark.parametrize("config", [None, {"applications": [{"id": "Other", "executable": "x.exe"}]}, ["bad"]])
def test_psf_without_usable_config_installs_nothing(tmp_path: Path, prefix: Path, config: object) -> None:
    with pytest.raises(msix.MsixError, match="None of the apps"):
        msix.install(_psf_package(tmp_path, config), prefix)
    assert not (_windowsapps(prefix) / FULL).exists()


def test_missing_program_file_installs_nothing(tmp_path: Path, prefix: Path) -> None:
    path = _pkg(tmp_path, man=B.manifest(apps=[B.app_xml(exe_rel="Missing\\Nope.exe")]))
    with pytest.raises(msix.MsixError, match="None of the apps"):
        msix.install(path, prefix)


# --------------------------------------------------------------------------- #
# Registry.dat (optional python3-hivex)
# --------------------------------------------------------------------------- #
class _Node:
    def __init__(self, name: str, values=(), children=()) -> None:
        self.name, self.values, self.children = name, list(values), list(children)


def _sz(text: str) -> bytes:
    return (text + "\x00").encode("utf-16-le")


TREES: Dict[str, _Node] = {
    "hive-machine": _Node("root", children=[_Node("REGISTRY", children=[
        _Node("MACHINE", children=[_Node("SOFTWARE", children=[_Node("Contoso", children=[
            _Node("PhotoEditor", values=[
                ("InstallDir", 1, _sz("[{AppVPackageRoot}]\\VFS\\ProgramFilesX64")),
                ("Plugins", 1, _sz('[{ProgramFilesX86}]\\Contoso "plugins"')),
                ("Version", 4, (5).to_bytes(4, "little")),
                ("Blob", 3, b"\x01\x02"),
                ("", 1, _sz("hello")),
            ])])])]),
        _Node("USER", children=[_Node("[{AppVCurrentUserSID}]", children=[_Node("Software", children=[
            _Node("Contoso", values=[("Theme", 1, _sz("dark"))])])])]),
    ])]),
    "hive-user": _Node("root", children=[_Node("Software", children=[
        _Node("Contoso", values=[("Recent", 7, _sz("a") + _sz("b"))])])]),
    "hive-classes": _Node("root", children=[_Node(".cphoto", values=[("", 1, _sz("Contoso.Photo"))])]),
}


def _fake_hivex() -> types.ModuleType:
    mod = types.ModuleType("hivex")

    class Hivex:
        def __init__(self, filename: str, *args: object, **kwargs: object) -> None:
            self._root = TREES[Path(filename).read_bytes().decode("ascii")]

        def root(self) -> _Node:
            return self._root

        def node_name(self, node: _Node) -> str:
            return node.name

        def node_children(self, node: _Node) -> List[_Node]:
            return list(node.children)

        def node_values(self, node: _Node) -> list:
            return list(node.values)

        def value_key(self, value: tuple) -> str:
            return value[0]

        def value_value(self, value: tuple) -> tuple:
            return value[1], value[2]

    mod.Hivex = Hivex  # type: ignore[attr-defined]
    return mod


def _registry_package(tmp_path: Path) -> Path:
    files = dict(B.desktop_files(), **{"Registry.dat": b"hive-machine", "User.dat": b"hive-user",
                                       "UserClasses.dat": b"hive-classes"})
    return _pkg(tmp_path, files=files)


def test_registry_import_with_hivex(tmp_path: Path, prefix: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setitem(sys.modules, "hivex", _fake_hivex())
    inst = msix.install(_registry_package(tmp_path), prefix)
    assert [p.name for p in inst.reg_files] == ["Registry.reg", "User.reg", "UserClasses.reg"]
    assert all(p.parent == prefix / ".lindos-msix" / FULL for p in inst.reg_files)
    raw = inst.reg_files[0].read_bytes()
    assert raw[:2] == b"\xff\xfe"
    text = raw.decode("utf-16")
    root = msix.package_root_windows(inst.info).replace("\\", "\\\\")
    assert text.startswith("Windows Registry Editor Version 5.00\r\n")
    assert "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Contoso\\PhotoEditor]" in text
    assert f'"InstallDir"="{root}\\\\VFS\\\\ProgramFilesX64"' in text
    assert '"Plugins"="C:\\\\Program Files (x86)\\\\Contoso \\"plugins\\""' in text
    assert '"Version"=dword:00000005' in text
    assert '"Blob"=hex:01,02' in text
    assert '@="hello"' in text
    assert "[HKEY_CURRENT_USER\\Software\\Contoso]" in text and '"Theme"="dark"' in text
    user = inst.reg_files[1].read_bytes().decode("utf-16")
    assert "[HKEY_CURRENT_USER\\Software\\Contoso]" in user and '"Recent"=hex(7):' in user
    classes = inst.reg_files[2].read_bytes().decode("utf-16")
    assert "[HKEY_CURRENT_USER\\Software\\Classes\\.cphoto]" in classes and '@="Contoso.Photo"' in classes
    assert any("registry settings were converted" in n for n in inst.notes)


def test_registry_without_hivex_is_a_warning_not_a_failure(tmp_path: Path, prefix: Path,
                                                           monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setitem(sys.modules, "hivex", None)  # import hivex -> ImportError
    inst = msix.install(_registry_package(tmp_path), prefix)
    assert inst.reg_files == []
    assert any("python3-hivex" in n for n in inst.notes)
    assert inst.apps  # the app itself is installed


def test_broken_hive_is_a_note(tmp_path: Path, prefix: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setitem(sys.modules, "hivex", _fake_hivex())
    files = dict(B.desktop_files(), **{"Registry.dat": b"not-a-known-hive"})
    inst = msix.install(_pkg(tmp_path, files=files), prefix)
    assert inst.reg_files == [] and any("could not be read" in n for n in inst.notes)


# --------------------------------------------------------------------------- #
# CLI and honesty
# --------------------------------------------------------------------------- #
def test_cli_inspect_json_and_exit_codes(pkg: Path, tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    assert msix.main(["inspect", str(pkg), "--json"]) == 0
    data = json.loads(capsys.readouterr().out)
    assert data["status"] == "partial" and data["package_full_name"] == FULL
    uwp = _pkg(tmp_path, "uwp.msix", files={"u.exe": B.exe()},
               man=B.manifest(apps=[B.app_xml(exe_rel="u.exe", attrs='EntryPoint="U.App"')]))
    assert msix.main(["inspect", str(uwp)]) == msix.EXIT_UNSUPPORTED
    assert "UWP" in capsys.readouterr().out
    assert msix.main(["classify", str(pkg)]) == 0
    assert capsys.readouterr().out.strip() == "package"
    assert msix.main(["inspect", str(tmp_path / "missing.msix"), "--json"]) == 1
    assert "error" in json.loads(capsys.readouterr().out)


def test_describe_is_plain_text(pkg: Path) -> None:
    text = msix.describe(msix.inspect(pkg))
    assert "Contoso Photo Editor" in text and "Signed (not verified)" in text and "win32" in text


def test_module_contains_no_evasion_tokens() -> None:
    source = Path(msix.__file__).read_text(encoding="utf-8").lower()
    for token in ("spoof", "hwid", "smbios", "sysinfo", "acpitable", "kvm=off", "hv-vendor-id", "vendor_id",
                  "<hidden", "decrypt("):
        assert token not in source, token
